# Design tokens - the single source of truth for color and type.
# bslib reads app_theme(), CSS reads the --app-* variables generated by
# css_root_vars(), and every plotly chart reads app_colors / app_plotly_layout.
# Change a hex here and the whole app (and the PDF report) follows.

app_colors <- list(
  primary      = "#1C5D99",  # confident consulting blue - the one strong accent
  primary_dark = "#12406B",
  ink          = "#1F2937",  # body text
  ink_muted    = "#64748B",
  bg           = "#F6F8FB",  # app canvas
  surface      = "#FFFFFF",  # cards
  border       = "#E2E8F0",
  positive     = "#1F9D66",  # cost decreases
  negative     = "#C4553B",  # cost increases (terracotta, not alarm red)
  warning      = "#B7791F",
  grid         = "rgba(28, 61, 90, 0.10)"
)

# Sequential ramp for the language treemap and comparison bars
app_colors$seq <- c("#DCE9F7", "#A9C8EA", "#76A7DD", "#4386CF", "#1C5D99", "#12406B")

#' n-color sequential palette drawn from the brand ramp
app_seq_palette <- function(n) {
  if (n <= 0) return(character(0))
  grDevices::colorRampPalette(app_colors$seq)(max(n, 2))[seq_len(max(n, 1))]
}

#' bslib theme built from the tokens
app_theme <- function() {
  bslib::bs_theme(
    version      = 5,
    bg           = app_colors$bg,
    fg           = app_colors$ink,
    primary      = app_colors$primary,
    secondary    = app_colors$ink_muted,
    success      = app_colors$positive,
    warning      = app_colors$warning,
    danger       = app_colors$negative,
    base_font    = bslib::font_google("Inter"),
    heading_font = bslib::font_google("Inter Tight"),
    code_font    = bslib::font_google("JetBrains Mono"),
    "border-radius" = "0.6rem"
  ) |>
    bslib::bs_add_variables(
      "card-border-color" = app_colors$border,
      "card-cap-bg"       = app_colors$surface,
      "card-bg"           = app_colors$surface,
      "navbar-light-bg"   = app_colors$surface
    )
}

#' Generate :root { --app-*: ... } CSS custom properties from app_colors
css_root_vars <- function() {
  scalar <- app_colors[!vapply(app_colors, function(x) length(x) > 1, logical(1))]
  vars <- paste0("  --app-", gsub("_", "-", names(scalar)), ": ",
                 unlist(scalar), ";", collapse = "\n")
  seq_vars <- paste0("  --app-seq-", seq_along(app_colors$seq), ": ",
                     app_colors$seq, ";", collapse = "\n")
  paste0(":root {\n", vars, "\n", seq_vars, "\n}")
}

# Shared plotly layout defaults for the light theme
app_plotly_layout <- list(
  paper_bgcolor = "transparent",
  plot_bgcolor  = "transparent",
  font = list(color = app_colors$ink, family = "Inter, sans-serif"),
  xaxis = list(
    color = app_colors$ink_muted,
    gridcolor = app_colors$grid,
    zerolinecolor = "rgba(28, 61, 90, 0.25)"
  ),
  yaxis = list(
    color = app_colors$ink_muted,
    gridcolor = app_colors$grid,
    zerolinecolor = "rgba(28, 61, 90, 0.25)"
  )
)
